import React, { useEffect, useMemo, useRef, useState } from 'react';
import { MantineProvider, createTheme, TextInput, Button, ActionIcon, Accordion, Select, Drawer, Badge, Tooltip } from '@mantine/core';
import { IconArrowUpRight, IconArrowRight, IconArrowLeft, IconSearch, IconX, IconBooks, IconLayoutGrid, IconListDetails, IconMenu2, IconRoute, IconArrowDown, IconExternalLink, IconBook2 } from '@tabler/icons-react';
import '@mantine/core/styles.css';
import '@fontsource-variable/dm-sans';
import '@fontsource-variable/newsreader';
import SpotlightCard from './components/SpotlightCard';
import catalog from './catalog.json';
import './styles.css';

const theme=createTheme({fontFamily:'"DM Sans Variable", sans-serif',primaryColor:'forest',colors:{forest:['#edf4ef','#d6e6dc','#afccbb','#85b197','#63997b','#4c8869','#3e795a','#30674b','#23563d','#173f35']},defaultRadius:'md',headings:{fontFamily:'"Newsreader Variable", Georgia, serif'},cursorType:'pointer'});
const collections=catalog.collections;
const sourceCollections=collections.filter(c=>!['core','next'].includes(c.id));
const normalize=s=>s.toLocaleLowerCase('tr').replace(/ı/g,'i').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const allRows=collections.flatMap(c=>c.groups.flatMap(g=>g.books.map(b=>({...b,collection:c,group:g.title}))));
const membershipMap=new Map();
allRows.forEach(b=>{if(!membershipMap.has(b.key)) membershipMap.set(b.key,new Set()); membershipMap.get(b.key).add(b.collection.short)});
const uniqueCount=membershipMap.size;
const matches=(b,q)=>normalize([b.title,b.author,b.tr||''].join(' ')).includes(normalize(q));
const parseHash=()=>{const id=decodeURIComponent(window.location.hash.slice(1));return collections.some(c=>c.id===id)||id==='sources'?id:'overview'};

function Mark({c,small=false}){return <span className={`source-mark mark-${c.id} ${small?'small':''}`} aria-hidden="true">{c.mark}</span>}
function Sidebar({active,navigate,close}){
 return <div className="sidebar-content"><a href="#overview" className="brand" onClick={e=>{e.preventDefault();navigate('overview');close?.()}}><span className="brand-icon"><IconBooks size={24} stroke={1.4}/></span><span>kitap<span className="brand-light">atlası</span><small>DÜŞÜNCEDEN UYGULAMAYA</small></span></a>
 <nav aria-label="Kitap kümeleri"><p className="nav-label">KİTAPLIĞINIZ</p><a href="#overview" className={`nav-link ${active==='overview'?'active':''}`} onClick={()=>close?.()}><IconLayoutGrid size={19}/><span>Tüm koleksiyonlar</span><span className="nav-count">{collections.length}</span></a>
 <p className="nav-label collections-label">KAYNAK SEÇKİLERİ</p>{sourceCollections.map((c,i)=><a href={`#${c.id}`} key={c.id} className={`nav-link ${active===c.id?'active':''}`} onClick={()=>close?.()}><span className="nav-number">{String(i+1).padStart(2,'0')}</span><span>{c.short}</span><span className="nav-count">{c.count}</span></a>)}
 <p className="nav-label collections-label">KİŞİSEL OKUMA ROTASI</p>{collections.filter(c=>['core','next'].includes(c.id)).map(c=><a href={`#${c.id}`} key={c.id} className={`nav-link ${active===c.id?'active':''}`} onClick={()=>close?.()}><IconRoute size={19}/><span>{c.short}</span><span className="nav-count">{c.count}</span></a>)}</nav>
 <div className="sidebar-bottom"><p>Birbirini tamamlayan<br/><em>düşünceler için.</em></p><a href="#sources" className={active==='sources'?'source-nav current':'source-nav'} onClick={()=>close?.()}><IconListDetails size={17}/> Kaynaklar ve kapsam <IconArrowUpRight size={15}/></a><div className="sidebar-date">KATALOG · EYLÜL 2026</div></div></div>
}
function CollectionCard({c,index}){
 return <SpotlightCard className={`collection-card collection-${c.id}`} spotlightColor="rgba(110, 132, 70, 0.11)"><a href={`#${c.id}`} className="card-link" aria-label={`${c.short}: ${c.count} kitap`}><div className="card-top"><Mark c={c}/><span className="card-index">{String(index+1).padStart(2,'0')}</span></div><p className="eyebrow">{c.tag}</p><h3>{c.short==='TIME'?'TIME’ın yönetim klasikleri':c.short==='Financial Times'?'Financial Times arşivi':c.short==='MIT Sloan'?'MIT Sloan okumaları':c.short==='Five Books'?'Five Books uzman seçkileri':c.short==='100 Best'?'100 Best Business Books':c.title}</h3><p className="card-description">{c.description}</p><div className="card-footer"><span><b>{c.count}</b> kitap <span className="middot">·</span> {c.groups.length===1?'Tam liste':`${c.groups.length} alt küme`}</span><span className="card-arrow"><IconArrowUpRight size={21}/></span></div></a></SpotlightCard>
}
function Overview(){
 return <><div className="page-intro"><div><p className="eyebrow"><span className="tiny-dot"/> BİR İŞLETME VE STRATEJİ KİTAPLIĞI</p><h1>İyi fikirler,<br/><em>bir araya gelince.</em></h1><p className="intro-description">Yönetimi anlamak, daha iyi karar vermek ve düşünceyi<br className="desktop-break"/> uygulamaya taşımak için bir okuma atlası.</p></div><div className="intro-stats"><div><strong>{collections.length.toString().padStart(2,'0')}</strong><span>kitap kümesi</span></div><div><strong>{uniqueCount}</strong><span>farklı eser</span></div></div></div>
 <SpotlightCard className="featured" spotlightColor="rgba(225, 238, 173, 0.15)"><div className="feature-number" aria-hidden="true">12<span>kitap</span></div><div className="featured-copy"><p className="eyebrow">NEREDEN BAŞLAMALI?</p><h2>Daha güçlü bir düşünme omurgası.</h2><p>TIME’dan dört klasik, onları tamamlayan sekiz kitap.<br/>Sistem, strateji ve yönetimi birlikte düşün.</p></div><Button component="a" href="#core" className="featured-button" rightSection={<IconArrowRight size={17}/>} size="md">Çekirdeği keşfet</Button></SpotlightCard>
 <div className="section-heading"><div><span className="section-kicker">01 — KAYNAK SEÇKİLERİ</span><h2>Altı kaynak, farklı bakışlar.</h2></div><span className="section-meta">Tam listeler, kendi kümelerinde</span></div><div className="collection-grid">{sourceCollections.map((c,i)=><CollectionCard c={c} index={i} key={c.id}/>)}</div>
 <div className="section-heading route-heading"><div><span className="section-kicker">02 — METİNDEN OKUMA ROTALARI</span><h2>Bir sonraki kitabına doğru.</h2></div></div><div className="route-grid">{collections.filter(c=>['core','next'].includes(c.id)).map(c=><a href={`#${c.id}`} className="route-card" key={c.id}><span className="route-count">{c.mark}</span><div><span className="eyebrow">{c.tag}</span><h3>{c.title}</h3><p>{c.description}</p></div><IconArrowUpRight size={22}/></a>)}</div></>
}
function BookRow({book:b,index,showCollection=false}){
 const memberships=[...(membershipMap.get(b.key)||[])];
 return <li className="book-row"><span className="book-index">{String(index+1).padStart(2,'0')}</span><div className="book-info"><h3>{b.title}</h3>{b.tr&&<span className="book-translation">{b.tr}</span>}<p className="book-author">{b.author}</p>{b.note&&<p className="book-note">{b.note}</p>}{showCollection&&<a className="search-origin" href={`#${b.collection.id}`}>{b.collection.short} <span> / {b.group}</span><IconArrowUpRight size={13}/></a>}</div><div className="book-right">{b.status&&<Badge variant="light" color={b.status==='Kazanan'?'forest':'gray'} className="award-badge">{b.status}</Badge>}{memberships.length>1&&<Tooltip label={memberships.join(' · ')} multiline w={240} withArrow><span className="membership">{memberships.length} kümede</span></Tooltip>}{b.source&&<Tooltip label="Kaynakta incele"><ActionIcon component="a" href={b.source} target="_blank" rel="noreferrer" variant="subtle" color="forest" size={40} aria-label={`${b.title} kaynağını aç`}><IconArrowUpRight size={20}/></ActionIcon></Tooltip>}</div></li>
}
function CollectionView({c}){
 const [selected,setSelected]=useState('all');const [status,setStatus]=useState('all');const [expanded,setExpanded]=useState([c.groups[0]?.title]);
 const shown=c.groups.filter(g=>selected==='all'||g.title===selected).map(g=>({...g,books:g.books.filter(b=>status==='all'||b.status===status)})).filter(g=>g.books.length);
 const count=shown.reduce((n,g)=>n+g.books.length,0);
 const allOpen=shown.every(g=>expanded.includes(g.title));
 return <><a href="#overview" className="back-link"><IconArrowLeft size={16}/> Koleksiyonlara dön</a><div className="collection-intro"><Mark c={c}/><div><p className="eyebrow">{c.tag}</p><h1>{c.title}</h1><p>{c.description}</p></div></div><div className="collection-summary"><span><b>{c.count}</b> kitap</span><span><b>{c.groups.length}</b> alt küme</span>{c.source&&<a href={c.source} target="_blank" rel="noreferrer">Özgün liste <IconExternalLink size={15}/></a>}</div><p className="scope-note">{c.note}</p>
 {c.guide&&<div className="guide"><IconBook2 size={23}/><div><span className="eyebrow">LİSTEYE BAŞLAMADAN ÖNCE</span><a href={c.guide.source} target="_blank" rel="noreferrer">{c.guide.title} <IconArrowUpRight size={16}/></a><p>{c.guide.author} · {c.count} kitaplık listenin dışında başlangıç rehberi</p></div></div>}
 {c.groups.length>1&&<div className="list-controls"><Select aria-label="Alt küme seç" label={c.id==='ft'?'Yıl':'Alt küme'} value={selected} onChange={value=>{setSelected(value||'all');if(value&&value!=='all')setExpanded(prev=>[...prev,value])}} data={[{value:'all',label:c.id==='ft'?'Bütün yıllar':'Bütün alt kümeler'},...c.groups.map(g=>({value:g.title,label:`${g.title} (${g.books.length})`}))]} allowDeselect={false} searchable className="group-select"/>{c.id==='ft'&&<Select label="Ödül durumu" value={status} onChange={v=>setStatus(v||'all')} data={[{value:'all',label:'Bütün durumlar'},'Kazanan','Kısa liste','Uzun liste']} allowDeselect={false}/>}<Button variant="subtle" color="forest" onClick={()=>setExpanded(allOpen?[]:shown.map(g=>g.title))} className="expand-button">{allOpen?'Tümünü daralt':'Tümünü aç'}</Button></div>}
 <div className="results-label" role="status">{count} kitap <span> · {shown.length} alt küme</span></div>
 {!shown.length?<p className="no-results">Bu seçimde kitap bulunamadı.</p>:c.groups.length===1?<ol className="book-list">{shown[0].books.map((b,i)=><BookRow book={b} index={i} key={b.title}/>)}</ol>:<Accordion multiple value={expanded} onChange={setExpanded} className="book-accordion" chevron={<IconArrowDown size={17}/>} chevronPosition="right">{shown.map(g=><Accordion.Item value={g.title} key={g.title}><Accordion.Control><span className="group-heading"><span>{g.title}{g.expert&&<small>{g.expert}</small>}{g.original&&<small>{g.original}</small>}</span><span className="group-count">{g.books.length} kitap</span></span></Accordion.Control><Accordion.Panel><ol className="book-list">{g.books.map((b,i)=><BookRow book={b} index={i} key={b.title}/>)}</ol>{g.source&&<a className="group-source" href={g.source} target="_blank" rel="noreferrer">Uzmanın seçkisini oku <IconArrowUpRight size={14}/></a>}</Accordion.Panel></Accordion.Item>)}</Accordion>}
 </>
}
function SearchResults({query,clear}){
 const results=useMemo(()=>allRows.filter(b=>matches(b,query)),[query]);
 const grouped=collections.map(c=>({c,rows:results.filter(b=>b.collection.id===c.id)})).filter(x=>x.rows.length);
 return <><div className="search-header"><p className="eyebrow">KİTAPLIĞIN TAMAMINDA ARA</p><h1>“{query}”</h1><p role="status">{new Set(results.map(b=>b.key)).size} eser · {grouped.length} kümede {results.length} eşleşme</p></div>{!results.length?<div className="empty-state"><IconSearch size={38} stroke={1}/><h2>Henüz bir eşleşme yok.</h2><p>Kitap adı, Türkçe karşılığı veya yazar soyadıyla tekrar dene.</p><Button variant="light" onClick={clear}>Aramayı temizle</Button></div>:grouped.map(({c,rows})=><section className="search-section" key={c.id}><a href={`#${c.id}`} className="search-collection-heading"><h2>{c.short}</h2><span>{rows.length} sonuç <IconArrowUpRight size={16}/></span></a><ol className="book-list">{rows.map((b,i)=><BookRow book={b} index={i} key={b.title+b.group} showCollection/>)}</ol></section>)}</>
}
function Sources(){return <><p className="eyebrow">KAYNAKLAR VE KAPSAM</p><h1>Her listenin<br/><em>bir bağlamı var.</em></h1><p className="sources-intro">Bu atlas, paylaşılan okuma metnindeki kümeleri ve o metinde işaret edilen kaynakların tam kitap listelerini bir araya getirir. Son kontrol: {catalog.updated}.</p><div className="source-notes">{sourceCollections.map(c=><section key={c.id}><Mark c={c} small/><div><h2>{c.title}</h2><p>{c.note}</p><a href={c.source} target="_blank" rel="noreferrer">Kaynağı incele <IconArrowUpRight size={15}/></a></div><span className="source-total">{c.count}</span></section>)}</div><div className="method-note"><h2>Sayıları nasıl okumalı?</h2><p>Aynı eser birden fazla seçkide bulunabilir. Küme sayıları o listedeki kitapları, ana sayfadaki eser sayısı tekrarları birleştirilmiş kataloğu gösterir. Farklı baskılar ve alt başlıklar mümkün olduğunca aynı eser altında eşleştirilmiştir.</p><p>Çekirdek seçki ve yakın vade rotası paylaşılan metne dayanır. Türkçe karşılıklar açıklama amaçlıdır. Kitapların özgün adları korunmuştur; tam kitap metinleri bu sitede yer almaz.</p><p>Financial Times durumları ve kaynak listeleri zamanla değişebilir. Bu sayfa, belirtilen tarihteki bir katalog kaydıdır.</p></div></>}
function App(){
 const [active,setActive]=useState(parseHash);const [query,setQuery]=useState('');const [mobile,setMobile]=useState(false);const searchRef=useRef(null);
 const navigate=id=>{window.location.hash=id;if(id===active)setQuery('')};
 useEffect(()=>{const onLink=e=>{const href=e.target.closest?.('a')?.getAttribute('href');if(href?.startsWith('#')&&href!=='#main-content')setQuery('')};document.addEventListener('click',onLink);return()=>document.removeEventListener('click',onLink)},[]);
 useEffect(()=>{const change=()=>{setActive(parseHash());setQuery('');setMobile(false);window.scrollTo({top:0,behavior:'instant'})};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change)},[]);
 useEffect(()=>{const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();searchRef.current?.focus()}if(e.key==='Escape')setQuery('')};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const c=collections.find(c=>c.id===active);
 return <><a href="#main-content" className="skip-link" onClick={e=>{e.preventDefault();const el=document.getElementById("main-content");el.focus();el.scrollIntoView()}}>İçeriğe geç</a><aside className="sidebar"><Sidebar active={active} navigate={navigate}/></aside><Drawer closeButtonProps={{'aria-label':'Menüyü kapat'}} opened={mobile} onClose={()=>setMobile(false)} title="Kitap Atlası" size={300} className="mobile-drawer"><Sidebar active={active} navigate={navigate} close={()=>setMobile(false)}/></Drawer><div className="workspace"><header className="topbar"><div className="topbar-location"><ActionIcon className="mobile-menu" variant="subtle" color="forest" size="lg" aria-label="Küme menüsünü aç" onClick={()=>setMobile(true)}><IconMenu2 size={23}/></ActionIcon><span>KİTAP ATLASI</span><span className="topbar-slash">/</span><span className="current-location">{c?.short|| (active==='sources'?'Kaynaklar':'Koleksiyonlar')}</span></div><span className="topbar-caption"><span className="tiny-dot"/> Merakla başlar.</span></header><main id="main-content" className="main" tabIndex={-1}><div className="search-wrap"><TextInput ref={searchRef} value={query} onChange={e=>setQuery(e.currentTarget.value)} aria-label="Tüm kitaplarda ve yazarlarda ara" placeholder="Bir kitap, bir yazar, yeni bir fikir…" leftSection={<IconSearch size={19} stroke={1.6}/>} rightSection={query?<ActionIcon aria-label="Aramayı temizle" onClick={()=>setQuery('')} variant="subtle" color="gray"><IconX size={16}/></ActionIcon>:<kbd>⌘ K</kbd>} size="md" className="global-search"/><span className="search-caption">Tüm koleksiyonlarda ara</span></div><div key={query.trim()?'search':active} className="view-content">{query.trim()?<SearchResults query={query.trim()} clear={()=>setQuery('')}/>:active==='overview'?<Overview/>:active==='sources'?<Sources/>:c?<CollectionView c={c} key={c.id}/>:<Overview/>}</div><footer className="footer"><span>kitapatlası <span className="footer-dot">/</span> Düşünceden uygulamaya.</span><a href="#sources">Kaynaklar ve kapsam <IconArrowUpRight size={14}/></a></footer></main></div></>
}
export default function KitapAtlas(){return <MantineProvider theme={theme} forceColorScheme="light"><App/></MantineProvider>}
